"""user model addition

Revision ID: d0457c491ab6
Revises: 25627a3e3183
Create Date: 2021-03-07 13:56:20.921959

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd0457c491ab6'
down_revision = '25627a3e3183'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('post', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blogs_category'), 'blogs', ['category'], unique=False)
    op.drop_index('ix_pitches_category', table_name='pitches')
    op.drop_table('pitches')
    op.add_column('comments', sa.Column('blog_id', sa.Integer(), nullable=False))
    op.drop_constraint('comments_pitch_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'blogs', ['blog_id'], ['id'])
    op.drop_column('comments', 'pitch_id')
    op.add_column('downvotes', sa.Column('blog_id', sa.Integer(), nullable=True))
    op.drop_constraint('downvotes_pitch_id_fkey', 'downvotes', type_='foreignkey')
    op.create_foreign_key(None, 'downvotes', 'blogs', ['blog_id'], ['id'])
    op.drop_column('downvotes', 'pitch_id')
    op.add_column('upvotes', sa.Column('blog_id', sa.Integer(), nullable=True))
    op.drop_constraint('upvotes_pitch_id_fkey', 'upvotes', type_='foreignkey')
    op.create_foreign_key(None, 'upvotes', 'blogs', ['blog_id'], ['id'])
    op.drop_column('upvotes', 'pitch_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upvotes', sa.Column('pitch_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'upvotes', type_='foreignkey')
    op.create_foreign_key('upvotes_pitch_id_fkey', 'upvotes', 'pitches', ['pitch_id'], ['id'])
    op.drop_column('upvotes', 'blog_id')
    op.add_column('downvotes', sa.Column('pitch_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'downvotes', type_='foreignkey')
    op.create_foreign_key('downvotes_pitch_id_fkey', 'downvotes', 'pitches', ['pitch_id'], ['id'])
    op.drop_column('downvotes', 'blog_id')
    op.add_column('comments', sa.Column('pitch_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_pitch_id_fkey', 'comments', 'pitches', ['pitch_id'], ['id'])
    op.drop_column('comments', 'blog_id')
    op.create_table('pitches',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('post', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='pitches_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='pitches_pkey')
    )
    op.create_index('ix_pitches_category', 'pitches', ['category'], unique=False)
    op.drop_index(op.f('ix_blogs_category'), table_name='blogs')
    op.drop_table('blogs')
    # ### end Alembic commands ###
